### PR TITLE
32129139: Try jest on yaem

### PR DESCRIPTION
**Pull request by DamienCassou**
This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/yaem/162)

### CODE REVIEW

**Review by BenjaminVanRyseghem — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/yaem/162)* status: all files reviewed, 1 unresolved discussion (waiting on @DamienCassou, @danglotb, @JohanBriglia, @josquindebaz, and @ValentinaVasile)

___
*[`jest.config.mjs` line 6 at r1](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-NuYuboe2JN3hXGwv1TT:-NuYuboe2JN3hXGwv1TU:b1zg8ws) ([raw file](https://github.com/foretagsplatsen/yaem/blob/ed14378fe44d203910211f966480a0a5feab604c/jest.config.mjs#L6)):*
> ```JavaScript
>  */
> 
> /** @type {import('jest').Config} */
> ```

nit: do we need this line?

**Review by josquindebaz — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/yaem/162)* status: all files reviewed, 1 unresolved discussion (waiting on @DamienCassou, @danglotb, @JohanBriglia, and @ValentinaVasile)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-NuYy76M8mHQ-3h13iN9):*
:partying_face:

**Review by JohanBriglia — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-:-NuZ2Ubn1FD6oH46LlWP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @DamienCassou, @danglotb, and @ValentinaVasile)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-NuYy76M8mHQ-3h13iN9):*
<details><summary><i>Previously, josquindebaz (Josquin Debaz) wrote…</i></summary><blockquote>

:partying_face:
</blockquote></details>

Did you already check how much code coverage we have? :grin:

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/yaem/162)* status: all files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem, @danglotb, and @ValentinaVasile)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-NuYy76M8mHQ-3h13iN9):*
<details><summary><i>Previously, JohanBriglia wrote…</i></summary><blockquote>

Did you already check how much code coverage we have? :grin:
</blockquote></details>



You can check that yourself in the CI results.
___
*[`jest.config.mjs` line 6 at r1](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-NuYuboe2JN3hXGwv1TT:-NuZF-GT8-rrhsXUdXi9:b2qvp2a) ([raw file](https://github.com/foretagsplatsen/yaem/blob/ed14378fe44d203910211f966480a0a5feab604c/jest.config.mjs#L6)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

nit: do we need this line?
</blockquote></details>

We don't *need* it but it's going to be convenient for anyone using LSP (including VS code and Emacs): it provides completion and documentation.

**Review by BenjaminVanRyseghem — APPROVED** [review]
> Reviewed 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/yaem/162)* status: all files reviewed, 1 unresolved discussion (waiting on @DamienCassou, @danglotb, and @ValentinaVasile)

___
*[`jest.config.mjs` line 6 at r1](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-NuYuboe2JN3hXGwv1TT:-Nuj3T-jEJDbhmj8i4rU:b-ciey3m) ([raw file](https://github.com/foretagsplatsen/yaem/blob/ed14378fe44d203910211f966480a0a5feab604c/jest.config.mjs#L6)):*
<details><summary><i>Previously, DamienCassou (Damien Cassou) wrote…</i></summary><blockquote>

We don't *need* it but it's going to be convenient for anyone using LSP (including VS code and Emacs): it provides completion and documentation.




</blockquote></details>

ok, thanks

**Review by BenjaminVanRyseghem — APPROVED** [review]
> Reviewed 10 of 10 files at r6, 1 of 1 files at r7, 9 of 9 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/yaem/162)* status: all files reviewed, 4 unresolved discussions (waiting on @DamienCassou, @danglotb, and @ValentinaVasile)

___
*[`babel.config.cjs` line 17 at r4](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-Nv27kRw7MxMIfp5vhNo:-Nv27kRw7MxMIfp5vhNp:b-8ir23q) ([raw file](https://github.com/foretagsplatsen/yaem/blob/e45796e852d006545b2aa4bd3673768dd8417794/babel.config.cjs#L17)):*
> ```JavaScript
> 				test: {
> 					plugins: [
> 						"rewire",
> ```

nit: why removing rewire?
___
*[`test/events.test.js` line 109 at r9](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-Nv28FsG65OFFD_7rinW:-Nv28FsG65OFFD_7rinX:bxtozdo) ([raw file](https://github.com/foretagsplatsen/yaem/blob/8ff795c745556b4ab21f3b182c99c9462a5d43b2/test/events.test.js#L109)):*
> ```JavaScript
> 	});
> 
> 	it("un-Bind callback using unbind", () => {
> ```

nit: unbinds?
___
*[`test/events.test.js` line 175 at r9](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-Nv28Nr10HZ73-DiAOn4:-Nv28Nr20yJxiLlxUgus:bu0tbqu) ([raw file](https://github.com/foretagsplatsen/yaem/blob/8ff795c745556b4ab21f3b182c99c9462a5d43b2/test/events.test.js#L175)):*
> ```JavaScript
> 	});
> 
> 	it("event Category can bind callback to named event using register", () => {
> ```

nit: shouldn't tests start with a verb?

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/yaem/162)* status: all files reviewed, 3 unresolved discussions (waiting on @BenjaminVanRyseghem, @danglotb, and @ValentinaVasile)

___
*[`babel.config.cjs` line 17 at r4](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-Nv27kRw7MxMIfp5vhNo:-Nv29tGY1ksxAS-bABDN:b-t680t0) ([raw file](https://github.com/foretagsplatsen/yaem/blob/e45796e852d006545b2aa4bd3673768dd8417794/babel.config.cjs#L17)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

nit: why removing rewire?
</blockquote></details>

it's not necessary to make the tests pass ;-). I have nothing against adding it back later but I'm keeping the stack as small as possible for now
___
*[`test/events.test.js` line 109 at r9](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-Nv28FsG65OFFD_7rinW:-Nv2ADCT5ZiLs6MDDcvp:b-y467vj) ([raw file](https://github.com/foretagsplatsen/yaem/blob/8ff795c745556b4ab21f3b182c99c9462a5d43b2/test/events.test.js#L109)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

nit: unbinds?
</blockquote></details>

these changes were done automatically by [eslint plugins](https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/prefer-lowercase-title.md) (not yet enabled in this PR because I have a [dedicated one in dev-doc](https://github.com/foretagsplatsen/dev-documentation/pull/99)). I agree more changes are necessary to make the code follow the guideline. It feels out of scope though.
___
*[`test/events.test.js` line 175 at r9](https://reviewable.io/reviews/foretagsplatsen/yaem/162#-Nv28Nr10HZ73-DiAOn4:-Nv2AXi83633bXLjep3L:b-uitnf8) ([raw file](https://github.com/foretagsplatsen/yaem/blob/8ff795c745556b4ab21f3b182c99c9462a5d43b2/test/events.test.js#L175)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

nit: shouldn't tests start with a verb?
</blockquote></details>

definitely. In this case, I think we need a dedicated `describe()` block and maybe even a dedicated test file. This is out of scope of this PR though. This change was done automatically by eslint. https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/prefer-lowercase-title.md

**Pull request merged**
